trigger:
- main

variables:
- name: BuildParameters.azureContainerRegistry
  value: '{"loginServer":"crgtl000hubthornelabsp01.azurecr.io", "id": "/subscriptions/ec85a53c-a825-4b1c-9861-ae30eeb92c9b/resourceGroups/rsg-tl000-hub-containers-p01/providers/Microsoft.ContainerRegistry/registries/crgtl000hubthornelabsp01"}'

resources:
  repositories:
  - repository: self
    type: git
    ref: main

jobs:
- job: Job_1
  displayName: AGENT JOB 1 PROD
  pool:
    name: 'tlaksprodpool'
    
  steps:
  - checkout: self

  - task: CopyFiles@2
    displayName: 'Copy docker compose files to root for build'
    inputs:
      SourceFolder: 'deployments/kb/compose'
      Contents: | 
        *prod.yml
      TargetFolder: '$(Build.Repository.LocalPath)'
      OverWrite: true  

  - task: AzureCLI@1
    displayName: 'Azure CLI Upload Container Deployment File'
    inputs:
      azureSubscription: 'sc-thornelabs-storage-p01'
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob upload --overwrite true --account-name statl000hubblobstorep01 --container-name blob-general-p01 --file deployments/kb/release/deploy-kb-prod.json --name deploy-kb-prod.json --account-key 3gnTW8VmS8mg+azpG9aiJKrUzJ1CTa3mSEfYDPZF1TEm06VOidEhqo+hurjpJvNPa21PG8z0t1o2+AStytpwGw==
 
  - task: DockerCompose@0
    displayName: Docker Compose
    inputs:
      azureSubscriptionEndpoint: sc-thornelabs-containers-p01
      azureContainerRegistry: $(BuildParameters.azureContainerRegistry)
      dockerComposeFile: docker-compose-kb-prod.yml
      projectName: 'compose-kb-server'      
      dockerComposeCommand: up --build --no-start

  - task: DockerCompose@0
    displayName: Push services
    inputs:
      azureSubscriptionEndpoint: sc-thornelabs-containers-p01
      azureContainerRegistry: $(BuildParameters.azureContainerRegistry)
      dockerComposeFile: docker-compose-kb-prod.yml
      projectName: 'compose-kb-server'      
      action: Push services   

  - task: Kubernetes@1
    displayName: Deploy to AKS 
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'sc-thornelabs-devops-aks-p01'
      azureResourceGroup: 'rsg-tl000-spk-akscluster-p01'
      kubernetesCluster: 'aks-tl000-spk-akscluster-p01'
      command: 'apply'
      namespace: 'thornehealthlab'
      arguments: '-f deployments/kb/kube/deploy-kb-aks-prod.yaml'


